apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/cloud_user/kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: coh-proxy
  name: coh-proxy-internal
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8282
  selector:
    io.kompose.service: coh-proxy
status:
  loadBalancer: {}
