apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/jplaroche_2017/kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: coh-wka1
  name: coh-wka1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: coh-wka1
    spec:
      containers:
      - env:
        - name: COH_OPTS
          value: -Dcoherence.wka=coh-wka1
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: gcr.io/superb-reporter-256719/coh_domain_poc:latest
        name: coh-wka1
        resources: {}
        volumeMounts:
        - mountPath: /tmp/coherence-archive
          name: coherence-share-claim
      restartPolicy: Always
      volumes:
      - name: coherence-share-claim
        persistentVolumeClaim:
          claimName: coherence-share-claim
status: {}
