apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/jplaroche_2017/kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: coh-mbean
  name: coh-mbean
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: coh-mbean
    spec:
      containers:
      - args:
        - mbean
        env:
        - name: JMX_OPTS
          value: -Dcoherence.management.remote.connectionport=3011 -Dcoherence.management.remote.registryport=9011
        - name: COH_OPTS
          value: -Dcoherence.wka=coh-wka1 -Dcoherence.wka2=coh-wka2
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: gcr.io/superb-reporter-256719/coh_domain_poc:latest
        name: coh-mbean
        ports:
        - containerPort: 9011
        - containerPort: 3011
        resources: {}
        volumeMounts:
        - mountPath: /tmp/coherence-archive
          name: coherence-share-claim
      restartPolicy: Always
      volumes:
      - name: coherence-share-claim
        persistentVolumeClaim:
          claimName: coherence-share-claim
status: {}
