apiVersion: v1
kind: PersistentVolume
metadata:
  name: coherence-share
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /export/coherence_share
    server: 10.162.15.206
